import { Inter } from "next/font/google";
import { SocketContextProvider } from "@/context/SocketContext";
import background_img from "@/public/images/background.png";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SocketContextProvider>
        <body className={inter.className}>
          <main className="main">
            <Image
              src={background_img}
              className="background_img"
              alt="background img"
            />
            <div className="container">{children}</div>
          </main>
        </body>
      </SocketContextProvider>
    </html>
  );
}
